services:

  db:
    image: mysql:8.4
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springbootdb
    ports:
      - 3306:3306