services:

  db:
    image: mysql:9.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springbootdb
    ports:
      - 3306:3306